import { TimelineItemType } from "./Timeline.types";

export const nightTimeline: TimelineItemType[] = [
  {
    icon: "/icons/rx-bus.svg",
    title: "پذیرش اتوبوس‌ها",
    start: "۱۳:۰۰    ",
    end: "۱۴:۰۰",
    type: "icon",
  },
  {
    icon: "/icons/rx-bus.svg",
    title: "حرکت اتوبوس‌ها",
    start: "۱۴:۰۰",
    end: "۱۸:۰۰",
    type: "icon",
  },
  {
    icon: "/icons/hotel.svg",
    title: "تحویل اتاق‌ها و استراحت",
    start: "۱۸:۰۰",
    end: "۱۹:۳۰",
    type: "icon",
  },
  {
    icon: "/icons/fire.svg",
    title: "ویژه برنامه‌ی شب",
    start: "۱۹:۳۰",
    end: "۲۱:۳۰",
    type: "icon",
  },
];

export const confDayTimeline: TimelineItemType[] = [
  {
    icon: "/icons/food.svg",
    title: "صرف صبحانه در هتل",
    start: "۰۸:۰۰",
    end: "۰۹:۰۰",
    type: "icon",
  },
  {
    icon: "/icons/rx-bus.svg",
    title: "حرکت به سمت محل همایش",
    start: "۰۹:۰۰",
    end: "۱۰:۰۰",
    type: "icon",
  },
  {
    icon: "/icons/acceptance.svg",
    title: "پذیرش همایش",
    start: "۱۰:۰۰",
    end: "۱۱:۰۰",
    type: "icon",
    color: "#22C55E",
  },
  {
    icon: "/icons/mic.svg",
    title: "مقدمه و معرفی همایش",
    start: "۱۱:۰۰",
    end: "۱۱:۱۰",
    type: "icon",
  },
  {
    profile: "/speakers/amir-kabiri.jpg",
    speaker: "امیر کبیری",
    title: "معماری فرانت اند دیجیکالا برای مدیریت ترافیک کلان",
    start: "۱۱:۱۵",
    end: "۱۱:۳۵",
    type: "speaker",
    link: "https://linkedin.com/in/amir-kabiri/",
  },
  {
    profile: "/speakers/pouria.jpg",
    speaker: "پوریا باباعلی",
    title: "بدهی فنی",
    start: "۱۱:۴۰",
    end: "۱۲:۰۰",
    type: "speaker",
    link: "https://www.linkedin.com/in/pouriya-babaali/",
  },
  {
    profile: "/speakers/hossein-mousavi.jpeg",
    speaker: "حسین موسوی",
    title: "حل مساله در مهندسی نرم‌افزار",
    start: "۱۲:۰۵",
    end: "۱۲:۲۵",
    type: "speaker",
    link: "https://linkedin.com/in/hossein13mousavi/",
  },
  {
    profile: "/speakers/mohammadreza-iranmanesh.webp",
    speaker: "محمدرضا ایرانمنش",
    title: "از توسعه تا نگهداری",
    start: "۱۲:۳۰",
    end: "۱۲:۵۰",
    type: "speaker",
    link: "https://linkedin.com/in/mohammadrezairanmanesh/",
  },
  {
    icon: "/icons/food.svg",
    title: "نهار و استراحت",
    start: "۱۲:۵۵",
    end: "۱۴:۱۰",
    type: "icon",
  },
  {
    profile: "/speakers/hesam.jpg",
    speaker: "حسام موسوی",
    title: "یک برنامه‌نویس برنده، بیزینسشو میسازه!",
    start: "۱۴:۱۰",
    end: "۱۴:۳۰",
    type: "speaker",
    link: "https://linkedin.com/in/hesam-mousavi-305454ab/",
  },
  {
    profile: "/speakers/behnia-azaad.webp",
    speaker: "بهنیا آزاد",
    title: "اندر مصائب تایپ اسکریپت در استارتاپ ها",
    start: "۱۴:۳۵",
    end: "۱۴:۵۵",
    type: "speaker",
    link: "https://linkedin.com/in/behniya-azad/",
  },
  {
    profile: "/speakers/samane-yaghoobi.webp",
    speaker: "سمانه یعقوبی",
    title: "معماری فرانت اند مقیاس پذیر در تیم های چابک",
    start: "۱۵:۰۰",
    end: "۱۵:۲۰",
    type: "speaker",
    link: "https://linkedin.com/in/samaneyaghoobi/",
  },
  {
    profile: "/speakers/mahmoud-sahebi.webp",
    speaker: "محمود صاحبی",
    title: "مسیر من برای انتخاب استک",
    start: "۱۵:۲۵",
    end: "۱۵:۴۵",
    type: "speaker",
    link: "https://linkedin.com/in/m-sahebi/",
  },
  {
    icon: "/icons/caffe.svg",
    title: "استراحت عصر",
    start: "۱۵:۵۰",
    end: "۱۶:۲۰",
    type: "icon",
  },
  {
    icon: "/icons/group.svg",
    title: "پنل گفت‌وگو",
    start: "۱۶:۲۵",
    end: "۱۷:۲۵",
    type: "icon",
  },
  {
    icon: "/icons/stars.svg",
    title: "اختتامیه و اهدای جوایز",
    start: "۱۷:۲۵",
    end: "۱۸:۰۰",
    type: "icon",
    color: "#F97316",
  },
];
