name: Pull request comment after merge
on:
  pull_request:
    types:
      - closed

jobs:
  comment:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.event.pull_request.user.login }}
    steps:
      - name: dump env
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thank you ${{ env.USERNAME }}!'
            })
