name: Pull request comment after merge
on:
  pull_request:
    types:
      - closed

jobs:
  comment:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.event.pull_request.user.login }}
      USER_URL: ${{ github.event.pull_request.user.html_url }}
    steps:
      - name: "Comment on the PR"
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thank you @[${{ env.USERNAME }}](${{ env.USER_URL }})!'
            })
