name: Tests

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - submitted

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint
      - name: ✅ GOOD JOB 👌
        run: echo "✅ GOOD JOB 👌"
